AllCops:
  TargetRubyVersion: 2.3
LineLength:
  Max: 250
Documentation:
  Enabled: false
MethodLength:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
AbcSize:
  Enabled: false
PerceivedComplexity:
  Enabled: false
ClassLength:
  Max: 180
